package tests;

import com.codename1.testing.AbstractTest;

import com.codename1.ui.Display;

public class UnnamedTest2 extends AbstractTest {
    public boolean runTest() throws Exception {
        waitForFormTitle("TodoCatalyst 300 [350]");
        clickButtonByPath((String)null);
        clickButtonByLabel("Lists");
        waitForFormTitle("TodoCatalyst 300 [350]");
        waitForFormTitle("Lists");
        clickButtonByPath(new int[]{0, 0, 0, 2, 0, 1, 1});
        waitForFormTitle("catTestElements");
        clickButtonByLabel("[1]");
        clickButtonByPath(new int[]{0, 0, 0, 2, 0, 3, 2});
        waitForFormTitle("test2");
        clickButtonByLabel("<click to set an alarm>");
        waitForFormTitle("");
        selectInList(new int[]{0, 4}, 9);
        clickButtonByLabel("OK");
        waitForFormTitle("test2");
        assertTextArea("test2");
        assertTextArea("");
        assertTextArea("Setting 'Time spent' will automatically set Task status to ONGOING");
        assertTextArea("");
        assertTextArea("");
        assertTextArea("Value per hour is calculated as Value divided by Estimated time, and once work has started by the sum of Remaining time and Time spent.");
        assertTextArea("Set automatically when using the timer");
        assertTextArea("Set automatically when a task is completed");
        assertTextArea("List: catTestElements");
        assertTextArea("");
        clickButtonByPath(new int[]{0, 0, 0, 1, 0});
        waitForFormTitle("Select");
        pointerPress(0.078125f, 0.26458332f, (String)null);
        waitFor(534);
        pointerRelease(0.078125f, 0.26458332f, (String)null);
        clickButtonByLabel("Created");
        waitForFormTitle("test2");
        clickButtonByLabel("Time");
        clickButtonByLabel("00:00");
        waitForFormTitle("");
        clickButtonByLabel("OK");
        waitForFormTitle("test2");
        clickButtonByLabel("00:00");
        waitForFormTitle("");
        selectInList(new int[]{0, 2}, 1);
        clickButtonByLabel("OK");
        waitForFormTitle("test2");
        clickButtonByPath(new int[]{0, 0, 1, 1, 1, 0});
        waitForFormTitle("");
        pointerPress(0.728125f, 0.17083333f, (String)null);
        waitFor(143);
        pointerRelease(0.728125f, 0.17083333f, (String)null);
        waitForFormTitle("test2");
        clickButtonByPath(new int[]{0, 0, 1, 1, 1, 0});
        waitForFormTitle("");
        clickButtonByLabel("OK");
        waitForFormTitle("test2");
        clickButtonByPath(new int[]{0, 0, 1, 1, 1, 0});
        waitForFormTitle("");
        clickButtonByLabel("OK");
        waitForFormTitle("test2");
        goBack();
        waitForFormTitle("catTestElements");
        clickButtonByPath((String)null);
        waitForFormTitle("Timer");
        clickButtonByPath(new int[]{0, 2, 0, 0});
        clickButtonByPath(new int[]{0, 2, 0, 0});
        assertTextArea("List: "catTestElements"");
        assertTextArea("test2");
        assertTextArea("");
        assertTextArea("Next: "test3"");
        clickButtonByPath((String)null);
        setText(new int[]{0, 1, 1}, "test");
        pointerPress(0.184375f, 0.5106383f, new int[]{0, 2, 0});
        waitFor(142);
        pointerRelease(0.184375f, 0.5106383f, new int[]{0, 2, 0});
        clickButtonByLabel("Completed");
        screenshotTest("UnnamedTest2_1");
        return true;
    }
}
